### PR TITLE
fix: handle parsing of MetaMask gas estimation errors

### LINKED ISSUE #93: update error code `33`/`34` on `v3`
https://github.com/Swivel-Finance/swivel-js/blob/v3/src/errors/types.ts#L140

this has recently changed in https://github.com/Swivel-Finance/gost/pull/411/files#diff-c3915893626fd10d200b07c6395dacb833161d97998d71bc914908358138ffd6

### LINKED ISSUE #94: fix: handle MetaMask gas estimation errors
MetaMask `UNPREDICTABLE_GAS_LIMIT` errors are different from the JsonRpcProvider errors and are currently not parsed correctly by swivel-js

### PR DESCRIPTION
**Pull request by alexanderwende**
add type defs for MetaMask's `ProviderRpcError`;
change detection logic for `isUnpredictableGasLimitError`;
allow direct parsing of abi-encoded error data strings;
add `getExchangeRate` method to MarketPlace hoc;
fix Exception code 33 & 34;
update tests;

fixes #93
fixes #94

### CODE REVIEW

File: src/contracts/market-place.ts [hunk 1]
```diff
@@ -178,6 +178,19 @@ export class MarketPlace {
...
+     * Retrieve the exchange rate for a lending protocol and cToken/pool using Swivel's ICompounding abstraction.
+     *
+     * @param p - protocol enum value of the lending protocol associated with a swivel market
+     * @param a - address of the market's cToken
+     * @param t - optional transaction overrides
+     * @returns the exchange rate of the protocol's cToken/pool to underlying (the scale of the value depends on the protocol)
+     */
+    async getExchangeRate (p: Protocols, a: string, t: CallOverrides = {}): Promise<string> {
+
+        return unwrap<BigNumber>(await this.contract.functions.getExchangeRate(p, a, t)).toString();
```
Comment (robrobbins) [inline src/contracts/market-place.ts:192]: ICompounding has `exchangeRate` not `getExchangeRate`

https://github.com/Swivel-Finance/gost/blob/v3/test/libraries/Compounding.sol#L66

File: src/errors/types.ts [hunk 2]
```diff
@@ -86,11 +86,11 @@ export const EXCEPTION = {
     },
     20: {
         name: 'SWIVEL.ADDRESS.SET',
-        message: (e: Exception): string => `Swivel address already set.`,
+        message: (e: Exception): string => `Swivel address is already set.`,
```
Comment (robrobbins) [inline src/errors/types.ts:89]: i don't see a reason to make them verbose with things like `...is,` and ` already...`. more words in an error message don't make it a better message

but you do you. no real requests here, just my 2C

**Review by robrobbins — APPROVED** [review]
Approving as the only real change is, at some point, you'll need to use `exchangeRate` vs `getExchangeRate` -- not sure if what is deployed currently has `get...` or not

File: src/contracts/market-place.ts (hunk 1 above)
Comment (alexanderwende) [reply src/contracts/market-place.ts:192]: that's good to know, cause i already have `exchangeRate` and `interestRate` methods on the MarketPlace HOC, which are not calling the contract, but the rates helpers in `src/rates/`

i'll leave myself a comment here to review that later 👍

File: src/errors/types.ts (hunk 2 above)
Comment (alexanderwende) [reply src/errors/types.ts:89]: yeah, i wasn't sure about it either... 

my thinking was: when a user tries to set the swivel address and then gets an error message that reads "Swivel address set." - it almost looks like a confirmation, rather than an error...

especially when those messages hit the frontend and show up in a notification, things might get confusing?

@JTraversa any preferences from the product side of things?
